language: ruby
rvm:
- ruby-head
- 2.2.0
- 2.1.0
- 2.0.0
- 1.9.3
before_script:
  - psql -c 'create database scheduler_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: NYQP0tT/n8GvIKFSWdsKsCZwvYhfEHtO2bGzdN9Mc0gRdF60HC7q3aC+gH1QTDp57hXgdqQUkcrkALXrkAqMu94toEr0mo4rvVAow23RO2pKBu+oTmfBjrhJlXbYuMAjwL8dGLZxMk8Db6saN8Y4oZE9pxr+NgbEjrc4zTIlFGo=
  app: simple-sched
